environment:
  CONAN_USER_HOME: $(APPVEYOR_BUILD_FOLDER)

build_script:
  - ps: coin/provisioning/qtci-windows-10-x86/11-conan.ps1
  - ps: coin/provisioning/qtci-windows-10-x86_64/11-conan.ps1
  - ps: coin/provisioning/qtci-windows-7-x86/11-conan.ps1
  - ps: Get-ChildItem -Path "install" -Recurse -File

artifacts:
  - path: 'conan_manifests'
  - path: 'conanbuildinfos'
  - path: '.conan\data'
    name: 'conan_data'

deploy:
  - provider: BinTray
    username: qtbot
    api_key:
      secure: JVvpuPj2nNKm4MwCyvIw/WZFQzaDt14pMaehLRGplNvTlVvH+/rhxHG3PLXsY6S5
    subject: qtproject
    repo: coin-provisioning
    package: conan-packages
    version: $(APPVEYOR_REPO_TAG_NAME)
    publish: true
    on:
      APPVEYOR_REPO_TAG: true
