build: false

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          SCRIPT_PATH: "coin/provisioning/qtci-windows-10-x86/03-conan.ps1"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          SCRIPT_PATH: "coin/provisioning/qtci-windows-10-x86_64/03-conan.ps1"

install:
  - powershell.exe -NonInteractive -File %SCRIPT_PATH%

test_script:
  - echo Hello world
