build: false

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

test_script:
  - ps: coin/provisioning/qtci-windows-10-x86/03-conan.ps1
  - ps: coin/provisioning/qtci-windows-10-x86_64/03-conan.ps1
  - ps: coin/provisioning/qtci-windows-7-x86/03-conan.ps1
